# Generated by Django 6.0.6 on 2026-07-09 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_course_cover_image_remove_course_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Sesión')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('platform', models.CharField(choices=[('meet', 'Google Meet'), ('zoom', 'Zoom'), ('otro', 'Otro')], default='meet', max_length=20, verbose_name='Plataforma')),
                ('meeting_link', models.URLField(verbose_name='Enlace de la Reunión')),
                ('scheduled_date', models.DateField(verbose_name='Fecha Programada')),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='core.course', verbose_name='Curso')),
            ],
            options={
                'ordering': ['-scheduled_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Módulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.course', verbose_name='Curso')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Material')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file', models.FileField(upload_to='materials/%Y/%m/', verbose_name='Archivo')),
                ('material_type', models.CharField(choices=[('pdf', 'Documento PDF'), ('video', 'Video'), ('document', 'Documento'), ('other', 'Otro')], default='document', max_length=20, verbose_name='Tipo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.module', verbose_name='Módulo')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Instrucciones')),
                ('assignment_type', models.CharField(choices=[('tarea', 'Tarea'), ('evaluacion', 'Evaluación')], default='tarea', max_length=20, verbose_name='Tipo')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite de Entrega')),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Puntaje Máximo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.module', verbose_name='Módulo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/', verbose_name='Archivo Entregado')),
                ('text_content', models.TextField(blank=True, verbose_name='Respuesta de Texto')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrega')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Calificación')),
                ('feedback', models.TextField(blank=True, verbose_name='Retroalimentación del Docente')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Calificación')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignment', verbose_name='Tarea/Evaluación')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
