# Generated by Django 6.0.6 on 2026-07-09 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_livesession_module_material_assignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/docs/', verbose_name='Documento Guía'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('tarea', 'Tarea'), ('evaluacion', 'Evaluación'), ('examen_online', 'Examen Online (Plataforma)')], default='tarea', max_length=30, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Pregunta')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Opción Múltiple (Autocalificable)'), ('text', 'Texto (Desarrollo / Argumentación)'), ('file', 'Subida de Archivo')], default='multiple_choice', max_length=20, verbose_name='Tipo de Pregunta')),
                ('points', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Puntaje')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.assignment', verbose_name='Examen')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Opción')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Es correcta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.question', verbose_name='Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Respuesta de Texto')),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='submissions/exam_files/', verbose_name='Archivo Adjunto')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntaje Obtenido')),
                ('feedback', models.TextField(blank=True, verbose_name='Retroalimentación')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question', verbose_name='Pregunta')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.choice', verbose_name='Opción Seleccionada')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='core.submission', verbose_name='Entrega del Examen')),
            ],
            options={
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
