# Generated by Django 6.0.6 on 2026-07-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignment_attached_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible para estudiantes'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible para estudiantes'),
        ),
        migrations.AddField(
            model_name='module',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible para estudiantes'),
        ),
    ]
