# Generated by Django 6.0.6 on 2026-07-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assignment_is_visible_material_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='Imagen de Portada (Archivo)'),
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Imagen de Portada (URL)'),
        ),
    ]
