# Generated by Django 6.0.6 on 2026-07-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_cover_image_course_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presentation',
            field=models.TextField(blank=True, verbose_name='Presentación Docente'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/pictures/', verbose_name='Foto de Perfil'),
        ),
    ]
