# Generated by Django 6.0.6 on 2026-07-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_presentation_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='welcome_description',
            field=models.TextField(blank=True, verbose_name='Mensaje de Bienvenida'),
        ),
    ]
