# Generated by Django 6.0.6 on 2026-07-10 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course_welcome_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio del Examen')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin del Examen')),
                ('current_question_index', models.PositiveIntegerField(default=0, verbose_name='Pregunta Actual')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempt', to='core.submission', verbose_name='Entrega')),
            ],
        ),
    ]
