# Generated by Django 6.0.6 on 2026-07-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_assignment_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_teacher_edit_syllabus',
            field=models.BooleanField(default=False, verbose_name='Permitir al docente editar Sílabo y Evaluación'),
        ),
        migrations.AddField(
            model_name='course',
            name='capacities',
            field=models.TextField(blank=True, verbose_name='Capacidades'),
        ),
        migrations.AddField(
            model_name='course',
            name='evaluation_system_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/evaluations/', verbose_name='Sistema de Evaluación (Imagen)'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, verbose_name='Sílabo (Introducción y Metodología)'),
        ),
    ]
