# Generated by Django 6.0.6 on 2026-07-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_course_evaluation_system_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_phone',
            field=models.BooleanField(default=True, verbose_name='Mostrar teléfono a estudiantes'),
        ),
    ]
