# Generated by Django 6.0.6 on 2026-07-11 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_show_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Unidad')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_units', to='core.course', verbose_name='Curso')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
