# Generated by Django 6.0.6 on 2026-07-11 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_syllabusunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Aviso')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('publish_date', models.DateTimeField(verbose_name='Fecha de Publicación')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible para estudiantes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.module', verbose_name='Módulo')),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Foro')),
                ('content', models.TextField(verbose_name='Contenido del Foro')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible para estudiantes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='core.module', verbose_name='Módulo')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.moduleforum', verbose_name='Foro')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Enlace')),
                ('url', models.URLField(verbose_name='URL')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible para estudiantes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.module', verbose_name='Módulo')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
