# Generated by Django 6.0.6 on 2026-07-11 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_moduleannouncement_moduleforum_forumreply_modulelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumreply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_replies', to='core.forumreply', verbose_name='Respuesta Padre'),
        ),
    ]
