# Generated by Django 6.0.6 on 2026-07-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_forumreply_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='delivery_specifications',
            field=models.TextField(blank=True, verbose_name='Especificaciones de Entrega'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='evaluation_criteria',
            field=models.TextField(blank=True, verbose_name='Criterios de Evaluación'),
        ),
    ]
