# Generated by Django 6.0.6 on 2026-07-12 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_assignment_delivery_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Puntaje Máximo'),
        ),
        migrations.CreateModel(
            name='QuestionResponseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/exam_files/', verbose_name='Archivo Adjunto')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.questionresponse', verbose_name='Respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/%Y/%m/', verbose_name='Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.submission', verbose_name='Entrega')),
            ],
        ),
    ]
