# Generated by Django 6.0.6 on 2026-07-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_assignment_max_score_questionresponsefile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, help_text='Déjalo en 0 para intentos ilimitados.', verbose_name='Número de intentos permitidos'),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempts',
            field=models.PositiveIntegerField(default=1, verbose_name='Intentos realizados'),
        ),
    ]
