# Generated by Django 6.0.6 on 2026-07-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_assignment_max_attempts_submission_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleforum',
            name='forum_type',
            field=models.CharField(choices=[('abierto', 'Foro Abierto'), ('cerrado', 'Foro Cerrado')], default='abierto', help_text='En foros cerrados, el alumno debe responder primero para ver otras respuestas.', max_length=20, verbose_name='Tipo de Foro'),
        ),
    ]
