# Generated by Django 6.0.6 on 2026-07-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_moduleforum_forum_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='QHSE Academy', max_length=100, verbose_name='Nombre de la Empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platform/', verbose_name='Logo de la Empresa')),
                ('primary_color', models.CharField(default='#1B5E37', help_text='Opcional. Ej: #1B5E37', max_length=20, verbose_name='Color Principal (HEX)')),
            ],
            options={
                'verbose_name': 'Configuración de Plataforma',
                'verbose_name_plural': 'Configuraciones de Plataforma',
            },
        ),
    ]
