# Generated by Django 6.0.6 on 2026-07-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_platformsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='allow_teacher_edit_syllabus',
            field=models.BooleanField(default=True, verbose_name='Permitir al docente editar Sílabo y Evaluación'),
        ),
    ]
