# Generated by Django 6.0.6 on 2026-07-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_attendanceregister_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='choice_orders',
            field=models.JSONField(blank=True, default=dict, verbose_name='Orden de Opciones'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='question_order',
            field=models.JSONField(blank=True, default=list, verbose_name='Orden de Preguntas'),
        ),
    ]
