# Generated by Django 6.0.6 on 2026-07-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_examattempt_choice_orders_examattempt_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_backtracking',
            field=models.BooleanField(default=False, verbose_name='Permitir retroceder a preguntas anteriores (Exámenes)'),
        ),
    ]
