# Generated by Django 6.0.6 on 2026-07-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_assignment_allow_backtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='show_all_questions',
            field=models.BooleanField(default=False, verbose_name='Mostrar todas las preguntas en una sola página (Exámenes)'),
        ),
    ]
