# Generated by Django 6.0.6 on 2026-07-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_assignment_show_all_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='show_all_questions',
            field=models.BooleanField(default=False, help_text='Si no marcas esta casilla, las preguntas se mostrarán una por una al estudiante.', verbose_name='Mostrar todas las preguntas en una sola página (Exámenes)'),
        ),
    ]
