# Generated by Django 6.0.6 on 2026-07-16 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_assignment_show_all_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='default_retention_months',
            field=models.PositiveIntegerField(default=12, help_text='Tiempo que un estudiante egresado puede ver su información. Se usa como valor inicial al crear cohortes.', verbose_name='Retención por defecto (meses)'),
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Promoción Enero 2026, Grupo B - 2026-II', max_length=100, verbose_name='Nombre de la Cohorte')),
                ('status', models.CharField(choices=[('active', 'En Curso'), ('completed', 'Finalizado')], default='active', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('retention_months', models.PositiveIntegerField(choices=[(6, '6 meses'), (12, '1 año'), (24, '2 años'), (36, '3 años')], default=12, help_text='Periodo durante el cual los estudiantes egresados pueden consultar su información.', verbose_name='Tiempo de Retención')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='core.course', verbose_name='Curso')),
                ('students', models.ManyToManyField(blank=True, related_name='cohort_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Estudiantes')),
            ],
            options={
                'verbose_name': 'Cohorte',
                'verbose_name_plural': 'Cohortes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='core.cohort', verbose_name='Cohorte'),
        ),
    ]
