# Generated by Django 6.0.6 on 2026-07-16 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_platformsetting_default_retention_months_cohort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='Si se especifica, esta sesión solo será visible para esta cohorte.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='core.cohort', verbose_name='Cohorte'),
        ),
        migrations.AddField(
            model_name='moduleannouncement',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='Si se especifica, este aviso solo será visible para esta cohorte.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.cohort', verbose_name='Cohorte'),
        ),
        migrations.AddField(
            model_name='moduleforum',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='Si se especifica, este foro solo será visible para esta cohorte.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='core.cohort', verbose_name='Cohorte'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programada'), ('active', 'Activa'), ('completed', 'Finalizada'), ('archived', 'Archivada')], default='active', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='CohortAssignmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite (Cohorte)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible para la cohorte')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_configs', to='core.assignment')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_configs', to='core.cohort')),
            ],
            options={
                'verbose_name': 'Configuración de Tarea por Cohorte',
                'verbose_name_plural': 'Configuraciones de Tareas por Cohorte',
                'unique_together': {('cohort', 'assignment')},
            },
        ),
    ]
