# Generated by Django 6.0.6 on 2026-07-16 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_livesession_cohort_moduleannouncement_cohort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='expired_students',
            field=models.ManyToManyField(blank=True, related_name='expired_cohort_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Estudiantes Expirados'),
        ),
    ]
