# Generated by Django 6.0.6 on 2026-07-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_cohort_expired_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='scheduled_end_date',
            field=models.DateField(blank=True, help_text='Si se establece, la cohorte se cerrará automáticamente en esta fecha.', null=True, verbose_name='Fecha Programada de Fin'),
        ),
    ]
