# Generated by Django 6.0.6 on 2026-07-17 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_cohort_scheduled_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frozen_modules', to='core.cohort', verbose_name='Cohorte (Congelado)'),
        ),
        migrations.AddField(
            model_name='syllabusunit',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frozen_syllabus', to='core.cohort', verbose_name='Cohorte (Congelado)'),
        ),
    ]
