# Generated by Django 6.0.6 on 2026-07-18 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_module_cohort_syllabusunit_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceregister',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_registers', to='core.cohort', verbose_name='Cohorte'),
        ),
    ]
