# Generated by Django 6.0.6 on 2026-07-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_supervisionaudit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='moduleannouncement',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='moduleforum',
            name='cohort',
        ),
        migrations.AddField(
            model_name='assignment',
            name='specific_cohorts',
            field=models.ManyToManyField(blank=True, related_name='specific_assignments', to='core.cohort', verbose_name='Grupos Específicos'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='target_type',
            field=models.CharField(choices=[('all', 'Todo el curso'), ('specific', 'Grupos específicos')], default='all', max_length=20, verbose_name='Visibilidad'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='specific_cohorts',
            field=models.ManyToManyField(blank=True, related_name='livesession_specific', to='core.cohort', verbose_name='Grupos Específicos'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='target_type',
            field=models.CharField(choices=[('all', 'Todo el curso'), ('specific', 'Grupos específicos')], default='all', max_length=20, verbose_name='Visibilidad'),
        ),
        migrations.AddField(
            model_name='material',
            name='specific_cohorts',
            field=models.ManyToManyField(blank=True, related_name='material_specific', to='core.cohort', verbose_name='Grupos Específicos'),
        ),
        migrations.AddField(
            model_name='material',
            name='target_type',
            field=models.CharField(choices=[('all', 'Todo el curso'), ('specific', 'Grupos específicos')], default='all', max_length=20, verbose_name='Visibilidad'),
        ),
        migrations.AddField(
            model_name='module',
            name='specific_cohorts',
            field=models.ManyToManyField(blank=True, related_name='module_specific', to='core.cohort', verbose_name='Grupos Específicos'),
        ),
        migrations.AddField(
            model_name='module',
            name='target_type',
            field=models.CharField(choices=[('all', 'Todo el curso'), ('specific', 'Grupos específicos')], default='all', max_length=20, verbose_name='Visibilidad'),
        ),
        migrations.AddField(
            model_name='moduleannouncement',
            name='specific_cohorts',
            field=models.ManyToManyField(blank=True, related_name='announcement_specific', to='core.cohort', verbose_name='Grupos Específicos'),
        ),
        migrations.AddField(
            model_name='moduleannouncement',
            name='target_type',
            field=models.CharField(choices=[('all', 'Todo el curso'), ('specific', 'Grupos específicos')], default='all', max_length=20, verbose_name='Visibilidad'),
        ),
        migrations.AddField(
            model_name='moduleforum',
            name='specific_cohorts',
            field=models.ManyToManyField(blank=True, related_name='forum_specific', to='core.cohort', verbose_name='Grupos Específicos'),
        ),
        migrations.AddField(
            model_name='moduleforum',
            name='target_type',
            field=models.CharField(choices=[('all', 'Todo el curso'), ('specific', 'Grupos específicos')], default='all', max_length=20, verbose_name='Visibilidad'),
        ),
        migrations.AddField(
            model_name='modulelink',
            name='specific_cohorts',
            field=models.ManyToManyField(blank=True, related_name='link_specific', to='core.cohort', verbose_name='Grupos Específicos'),
        ),
        migrations.AddField(
            model_name='modulelink',
            name='target_type',
            field=models.CharField(choices=[('all', 'Todo el curso'), ('specific', 'Grupos específicos')], default='all', max_length=20, verbose_name='Visibilidad'),
        ),
    ]
